drop table if exists `country` ;
create table `country` (
  `id` int(11) not null auto_increment,
  `iso` char(2) not null,
  `name` varchar(255) not null,
  `name_ar` varchar(255) not null,
  `iso3` char(3) default null,
  `country_code` int(5) not null,
  primary key (`id`)
) engine=myisam auto_increment=240 default charset=utf8;



INSERT INTO `country` VALUES(1     , 'AL'  ,  'Albania'                                         , 'ألبانيا'                                          ,  'ALB'     ,  355     );
INSERT INTO `country` VALUES(2     , 'DZ'  ,  'Algeria'                                         , 'الجزائر'                                          ,  'DZA'     ,  213     );
INSERT INTO `country` VALUES(3     , 'AS'  ,  'American Samoa'                                  , 'ساموا-الأمريكي'                                    ,  'ASM'     ,  1684    );
INSERT INTO `country` VALUES(4     , 'AD'  ,  'Andorra'                                         , 'أندورا'                                           ,  'AND'     ,  376     );
INSERT INTO `country` VALUES(5     , 'AO'  ,  'Angola'                                          , 'أنغولا'                                            ,  'AGO'     ,  244     );
INSERT INTO `country` VALUES(6     , 'AI'  ,  'Anguilla'                                        , 'أنغويلا'                                           ,  'AIA'     ,  1264    );
INSERT INTO `country` VALUES(7     , 'AQ'  ,  'Antarctica'                                      , 'أنتاركتيكا'                                       ,  null      ,  0       );
INSERT INTO `country` VALUES(8     , 'AG'  ,  'Antigua and Barbuda'                             , 'أنتيغوا وبربودا'                                  ,  'ATG'     ,  1268    );
INSERT INTO `country` VALUES(9     , 'AR'  ,  'Argentina'                                       , 'الأرجنتين'                                         ,  'ARG'     ,  54      );
INSERT INTO `country` VALUES(10    , 'AM'  ,  'Armenia'                                         , 'أرمينيا'                                          ,  'ARM'     ,  374     );
INSERT INTO `country` VALUES(11    , 'AW'  ,  'Aruba'                                           , 'أروبه'                                            ,  'ABW'     ,    297   );
INSERT INTO `country` VALUES(12    , 'AU'  ,  'Australia'                                       , 'أستراليا'                                         ,  'AUS'     ,    61    );
INSERT INTO `country` VALUES(13    , 'AT'  ,  'Austria'                                         , 'النمسا'                                           ,  'AUT'     ,    43    );
INSERT INTO `country` VALUES(14    , 'AZ'  ,  'Azerbaijan'                                      , 'أذربيجان'                                         ,  'AZE'     ,    994   );
INSERT INTO `country` VALUES(15    , 'BS'  ,  'Bahamas'                                         , 'الباهاماس'                                        ,  'BHS'     ,  1242    );
INSERT INTO `country` VALUES(16    , 'BH'  ,  'Bahrain'                                         , 'البحرين'                                          ,  'BHR'     ,  973     );
INSERT INTO `country` VALUES(17    , 'BD'  ,  'Bangladesh'                                      , 'بنغلاديش'                                          ,  'BGD'     ,  880     );
INSERT INTO `country` VALUES(18    , 'BB'  ,  'Barbados'                                        , 'بربادوس'                                          ,  'BRB'     ,  1246    );
INSERT INTO `country` VALUES(19    , 'BY'  ,  'Belarus'                                         , 'روسيا البيضاء'                                    ,  'BLR'     ,  375     );
INSERT INTO `country` VALUES(20    , 'BE'  ,  'Belgium'                                         , 'بلجيكا'                                           ,  'BEL'     ,  32      );
INSERT INTO `country` VALUES(21    , 'BZ'  ,  'Belize'                                          , 'بيليز'                                            ,  'BLZ'     ,  501     );
INSERT INTO `country` VALUES(22    , 'BJ'  ,  'Benin'                                           , 'بنين'                                             ,  'BEN'     ,  229     );
INSERT INTO `country` VALUES(23    , 'BM'  ,  'Bermuda'                                         , 'جزر برمودا'                                       ,  'BMU'     ,  1441    );
INSERT INTO `country` VALUES(24    , 'BT'  ,  'Bhutan'                                          , 'بوتان'                                            ,  'BTN'     ,  975     );
INSERT INTO `country` VALUES(25    , 'BO'  ,  'Bolivia'                                         , 'بوليفيا'                                          ,  'BOL'     ,  591     );
INSERT INTO `country` VALUES(26    , 'BA'  ,  'Bosnia and Herzegovina'                          , 'البوسنة و الهرسك'                                 ,  'BIH'     ,  387     );
INSERT INTO `country` VALUES(27    , 'BW'  ,  'Botswana'                                        , 'بوتسوانا'                                         ,  'BWA'     ,  267     );
INSERT INTO `country` VALUES(28    , 'BV'  ,  'Bouvet Island'                                   , 'جزيرة بوفيه'                                      ,  NULL      ,  0       );
INSERT INTO `country` VALUES(29    , 'BR'  ,  'Brazil'                                          , 'البرازيل'                                         ,  'BRA'     ,  55      );
INSERT INTO `country` VALUES(30    , 'IO'  ,  'British Indian Ocean Territory'                  , 'إقليم المحيط الهندي البريطاني'                    ,  NULL      ,  246     );
INSERT INTO `country` VALUES(31    , 'BN'  ,  'Brunei Darussalam'                               , 'بروني'                                            ,  'BRN'     ,  673     );
INSERT INTO `country` VALUES(32    , 'BG'  ,  'Bulgaria'                                        , 'بلغاريا'                                          ,  'BGR'     ,  359     );
INSERT INTO `country` VALUES(33    , 'BF'  ,  'Burkina Faso'                                    , 'بوركينا فاسو'                                     ,  'BFA'     ,  226     );
INSERT INTO `country` VALUES(34    , 'BI'  ,  'Burundi'                                         , 'بوروندي'                                          ,  'BDI'     ,  257     );
INSERT INTO `country` VALUES(35    , 'KH'  ,  'Cambodia'                                        , 'كمبوديا'                                          ,  'KHM'     ,  855     );
INSERT INTO `country` VALUES(36    , 'CM'  ,  'Cameroon'                                        , 'كاميرون'                                          ,  'CMR'     ,  237     );
INSERT INTO `country` VALUES(37    , 'CA'  ,  'Canada'                                          , 'كندا'                                             ,  'CAN'     ,  1       );
INSERT INTO `country` VALUES(38    , 'CV'  ,  'Cape Verde'                                      , 'الرأس الأخضر'                                      ,  'CPV'     ,  238     );
INSERT INTO `country` VALUES(39    , 'KY'  ,  'Cayman Islands'                                  , 'جزر كايمان'                                       ,  'CYM'     ,  1345    );
INSERT INTO `country` VALUES(40    , 'CF'  ,  'Central African Republic'                        , 'جمهورية أفريقيا الوسطى'                           ,  'CAF'     ,  236     );
INSERT INTO `country` VALUES(41    , 'TD'  ,  'Chad'                                            , 'تشاد'                                             ,  'TCD'     ,  235     );
INSERT INTO `country` VALUES(42    , 'CL'  ,  'Chile'                                           , 'شيلي'                                             ,  'CHL'     ,  56      );
INSERT INTO `country` VALUES(43    , 'CN'  ,  'China'                                           , 'الصين'                                            ,  'CHN'     ,  86      );
INSERT INTO `country` VALUES(44    , 'CX'  ,  'Christmas Island'                                , 'جزيرة عيد الميلاد'                                 ,  NULL      ,  61      );
INSERT INTO `country` VALUES(45    , 'CC'  ,  'Cocos (Keeling) Islands'                         , 'جزر كوكوس'                                        ,  NULL      ,  672     );
INSERT INTO `country` VALUES(46    , 'CO'  ,  'Colombia'                                        , 'كولومبيا'                                         ,  'COL'     ,  57      );
INSERT INTO `country` VALUES(47    , 'KM'  ,  'Comoros'                                         , 'جزر القمر'                                        ,  'COM'     ,  269     );
INSERT INTO `country` VALUES(48    , 'CG'  ,  'Congo'                                           , 'الكونغو'                                          ,  'COG'     ,  242     );
INSERT INTO `country` VALUES(49    , 'CK'  ,  'Cook Islands'                                    , 'جزر كوك'                                          ,  'COK'     ,  682     );
INSERT INTO `country` VALUES(50    , 'CR'  ,  'Costa Rica'                                      , 'كوستاريكا'                                        ,  'CRI'     ,  506     );
INSERT INTO `country` VALUES(51    , 'HR'  ,  'Croatia'                                         , 'كرواتيا'                                          ,  'HRV'     ,  385     );
INSERT INTO `country` VALUES(52    , 'CU'  ,  'Cuba'                                            , 'كوبا'                                             ,  'CUB'     ,  53      );
INSERT INTO `country` VALUES(53    , 'CY'  ,  'Cyprus'                                          , 'قبرص'                                             ,  'CYP'     ,  357     );
INSERT INTO `country` VALUES(54    , 'CZ'  ,  'Czech Republic'                                  , 'الجمهورية التشيكية'                               ,  'CZE'     ,  420     );
INSERT INTO `country` VALUES(55    , 'DK'  ,  'Denmark'                                         , 'الدانمارك'                                        ,  'DNK'     ,  45      );
INSERT INTO `country` VALUES(56    , 'DJ'  ,  'Djibouti'                                        , 'جيبوتي'                                           ,  'DJI'     ,  253     );
INSERT INTO `country` VALUES(57    , 'DM'  ,  'Dominica'                                        , 'دومينيكا'                                         ,  'DMA'     ,  1767    );
INSERT INTO `country` VALUES(58    , 'DO'  ,  'Dominican Republic'                              , 'الجمهورية الدومينيكية'                            ,  'DOM'     ,  1809    );
INSERT INTO `country` VALUES(59    , 'EC'  ,  'Ecuador'                                         , 'إكوادور'                                          ,  'ECU'     ,  593     );
INSERT INTO `country` VALUES(60    , 'EG'  ,  'Egypt'                                           , 'مصر'                                              ,  'EGY'     ,  20      );
INSERT INTO `country` VALUES(61    , 'SV'  ,  'El Salvador'                                     , 'إلسلفادور'                                        ,  'SLV'     ,  503     );
INSERT INTO `country` VALUES(62    , 'GQ'  ,  'Equatorial Guinea'                               , 'غينيا الاستوائي'                                   ,  'GNQ'     ,  240     );
INSERT INTO `country` VALUES(63    , 'ER'  ,  'Eritrea'                                         , 'إريتريا'                                          ,  'ERI'     ,  291     );
INSERT INTO `country` VALUES(64    , 'EE'  ,  'Estonia'                                         , 'استونيا'                                          ,  'EST'     ,  372     );
INSERT INTO `country` VALUES(65    , 'ET'  ,  'Ethiopia'                                        , 'أثيوبيا'                                          ,  'ETH'     ,  251     );
INSERT INTO `country` VALUES(66    , 'FK'  ,  'Falkland Islands (Malvinas)'                     , 'جزر فوكلاند'                                       ,  'FLK'     ,  500     );
INSERT INTO `country` VALUES(67    , 'FO'  ,  'Faroe Islands'                                   , 'جزر فارو'                                         ,  'FRO'     ,  298     );
INSERT INTO `country` VALUES(68    , 'FJ'  ,  'Fiji'                                            , 'فيجي'                                             ,  'FJI'     ,  679     );
INSERT INTO `country` VALUES(69    , 'FI'  ,  'Finland'                                         , 'فنلندا'                                           ,  'FIN'     ,  358     );
INSERT INTO `country` VALUES(70    , 'FR'  ,  'France'                                          , 'فرنسا'                                            ,  'FRA'     ,  33      );
INSERT INTO `country` VALUES(71    , 'GF'  ,  'French Guiana'                                   , 'غويانا الفرنسية'                                  ,  'GUF'     ,  594     );
INSERT INTO `country` VALUES(72    , 'PF'  ,  'French Polynesia'                                , 'بولينيزيا الفرنسية'                               ,  'PYF'     ,  689     );
INSERT INTO `country` VALUES(73    , 'TF'  ,  'French Southern and Antarctic Lands'             , 'أراض فرنسية جنوبية وأنتارتيكية'                   ,  NULL      ,  0       );
INSERT INTO `country` VALUES(74    , 'GA'  ,  'Gabon'                                           , 'الغابون'                                          ,  'GAB'     ,  241     );
INSERT INTO `country` VALUES(75    , 'GM'  ,  'Gambia'                                          , 'غامبيا'                                           ,  'GMB'     ,  220     );
INSERT INTO `country` VALUES(76    , 'GE'  ,  'Georgia'                                         , 'جيورجيا'                                          ,  'GEO'     ,  995     );
INSERT INTO `country` VALUES(77    , 'DE'  ,  'Germany'                                         , 'ألمانيا'                                          ,  'DEU'     ,  49      );
INSERT INTO `country` VALUES(78    , 'GH'  ,  'Ghana'                                           , 'غانا'                                             ,  'GHA'     ,  233     );
INSERT INTO `country` VALUES(79    , 'GI'  ,  'Gibraltar'                                       , 'جبل طارق'                                         ,  'GIB'     ,  350     );
INSERT INTO `country` VALUES(80    , 'GR'  ,  'Greece'                                          , 'اليونان'                                          ,  'GRC'     ,  30      );
INSERT INTO `country` VALUES(81    , 'GL'  ,  'Greenland'                                       , 'جرينلاند'                                          ,  'GRL'     ,  299     );
INSERT INTO `country` VALUES(82    , 'GD'  ,  'Grenada'                                         , 'غرينادا'                                          ,  'GRD'     ,  1473    );
INSERT INTO `country` VALUES(83    , 'GP'  ,  'Guadeloupe'                                      , 'جزر جوادلوب'                                      ,  'GLP'     ,  590     );
INSERT INTO `country` VALUES(84    , 'GU'  ,  'Guam'                                            , 'جوام'                                             ,  'GUM'     ,  1671    );
INSERT INTO `country` VALUES(85    , 'GT'  ,  'Guatemala'                                       , 'غواتيمال'                                         ,  'GTM'     ,  502     );
INSERT INTO `country` VALUES(86    , 'GN'  ,  'Guinea'                                          , 'غينيا'                                            ,  'GIN'     ,  224     );
INSERT INTO `country` VALUES(87    , 'GW'  ,  'Guinea-Bissau'                                   , 'غينيا-بيساو'                                      ,  'GNB'     ,  245     );
INSERT INTO `country` VALUES(88    , 'GY'  ,  'Guyana'                                          , 'غيانا'                                            ,  'GUY'     ,  592     );
INSERT INTO `country` VALUES(89    , 'HT'  ,  'Haiti'                                           , 'هايتي'                                            ,  'HTI'     ,  509     );
INSERT INTO `country` VALUES(90    , 'HM'  ,  'Heard and Mc Donald Islands'                     , 'جزيرة هيرد وجزر ماكدونالد'                        ,  NULL      ,  0       );
INSERT INTO `country` VALUES(91    , 'HN'  ,  'Honduras'                                        , 'هندوراس'                                          ,  'HND'     ,  504     );
INSERT INTO `country` VALUES(92    , 'HK'  ,  'Hong Kong'                                       , 'هونغ كونغ'                                        ,  'HKG'     ,  852     );
INSERT INTO `country` VALUES(93    , 'HU'  ,  'Hungary'                                         , 'المجر'                                            ,  'HUN'     ,  36      );
INSERT INTO `country` VALUES(94    , 'IS'  ,  'Iceland'                                         , 'آيسلندا'                                          ,  'ISL'     ,  354     );
INSERT INTO `country` VALUES(95    , 'IN'  ,  'India'                                           , 'الهند'                                            ,  'IND'     ,  91      );
INSERT INTO `country` VALUES(96    , 'ID'  ,  'Indonesia'                                       , 'أندونيسيا'                                        ,  'IDN'     ,  62      );
INSERT INTO `country` VALUES(97    , 'IR'  ,  'Iran'                                            , 'إيران'                                            ,  'IRN'     ,  98      );
INSERT INTO `country` VALUES(98    , 'IQ'  ,  'Iraq'                                            , 'العراق'                                           ,  'IRQ'     ,  964     );
INSERT INTO `country` VALUES(99    , 'IE'  ,  'Ireland'                                         , 'إيرلندا'                                          ,  'IRL'     ,  353     );
INSERT INTO `country` VALUES(100   , 'IT'  ,  'Italy'                                           , 'إيطاليا'                                          ,  'ITA'     ,  39      );
INSERT INTO `country` VALUES(101   , 'CI'  ,  'Ivory Coast'                                     , 'ساحل العاج'                                       ,  'CIV'     ,  225     );
INSERT INTO `country` VALUES(102   , 'JM'  ,  'Jamaica'                                         , 'جمايكا'                                           ,  'JAM'     ,  1876    );
INSERT INTO `country` VALUES(103   , 'JP'  ,  'Japan'                                           , 'اليابان'                                          ,  'JPN'     ,  81      );
INSERT INTO `country` VALUES(104   , 'JO'  ,  'Jordan'                                          , 'الأردن'                                            ,  'JOR'     ,  962     );
INSERT INTO `country` VALUES(105   , 'KZ'  ,  'Kazakhstan'                                      , 'كازاخستان'                                        ,  'KAZ'     ,  7       );
INSERT INTO `country` VALUES(106   , 'KE'  ,  'Kenya'                                           , 'كينيا'                                            ,  'KEN'     ,  254     );
INSERT INTO `country` VALUES(107   , 'KI'  ,  'Kiribati'                                        , 'كيريباتي'                                         ,  'KIR'     ,  686     );
INSERT INTO `country` VALUES(108   , 'KP'  ,  'Korea(North Korea)'                              , 'كوريا الشمالية'                                   ,  'PRK'     ,  850     );
INSERT INTO `country` VALUES(109   , 'KR'  ,  'Korea(South Korea)'                              , 'كوريا الجنوبية'                                   ,  'KOR'     ,  82      );
INSERT INTO `country` VALUES(110   , 'KW'  ,  'Kuwait'                                          , 'الكويت'                                           ,  'KWT'     ,  965     );
INSERT INTO `country` VALUES(111   , 'KG'  ,  'Kyrgyzstan'                                      , 'قيرغيزستان'                                       ,  'KGZ'     ,  996     );
INSERT INTO `country` VALUES(112   , 'LA'  ,  'Lao PDR'                                         , 'لاوس'                                              ,  'LAO'     ,  856     );
INSERT INTO `country` VALUES(113   , 'LV'  ,  'Latvia'                                          , 'لاتفيا'                                            ,  'LVA'     ,  371     );
INSERT INTO `country` VALUES(114   , 'LB'  ,  'Lebanon'                                         , 'لبنان'                                            ,  'LBN'     ,  961     );
INSERT INTO `country` VALUES(115   , 'LS'  ,  'Lesotho'                                         , 'ليسوتو'                                           ,  'LSO'     ,  266     );
INSERT INTO `country` VALUES(116   , 'LR'  ,  'Liberia'                                         , 'ليبيريا'                                          ,  'LBR'     ,  231     );
INSERT INTO `country` VALUES(117   , 'LY'  ,  'Libya'                                           , 'ليبيا'                                            ,  'LBY'     ,  218     );
INSERT INTO `country` VALUES(118   , 'LI'  ,  'Liechtenstein'                                   , 'ليختنشتين'                                        ,  'LIE'     ,  423     );
INSERT INTO `country` VALUES(119   , 'LT'  ,  'Lithuania'                                       , 'لتوانيا'                                          ,  'LTU'     ,  370     );
INSERT INTO `country` VALUES(120   , 'LU'  ,  'Luxembourg'                                      , 'لوكسمبورغ'                                        ,  'LUX'     ,  352     );
INSERT INTO `country` VALUES(121   , 'LK'  ,  'Sri Lanka'                                       , 'سريلانكا'                                          ,  'LKA'     ,  94      );
INSERT INTO `country` VALUES(122   , 'MO'  ,  'Macau'                                           , 'ماكاو'                                            ,  'MAC'     ,  853     );
INSERT INTO `country` VALUES(123   , 'MK'  ,  'Macedonia'                                       , 'مقدونيا'                                          ,  'MKD'     ,  389     );
INSERT INTO `country` VALUES(124   , 'MG'  ,  'Madagascar'                                      , 'مدغشقر'                                           ,  'MDG'     ,  261     );
INSERT INTO `country` VALUES(125   , 'MW'  ,  'Malawi'                                          , 'مالاوي'                                            ,  'MWI'     ,  265     );
INSERT INTO `country` VALUES(126   , 'MY'  ,  'Malaysia'                                        , 'ماليزيا'                                          ,  'MYS'     ,  60      );
INSERT INTO `country` VALUES(127   , 'MV'  ,  'Maldives'                                        , 'المالديف'                                         ,  'MDV'     ,  960     );
INSERT INTO `country` VALUES(128   , 'ML'  ,  'Mali'                                            , 'مالي'                                             ,  'MLI'     ,  223     );
INSERT INTO `country` VALUES(129   , 'MT'  ,  'Malta'                                           , 'مالطا'                                            ,  'MLT'     ,  356     );
INSERT INTO `country` VALUES(130   , 'MH'  ,  'Marshall Islands'                                , 'جزر مارشال'                                       ,  'MHL'     ,  692     );
INSERT INTO `country` VALUES(131   , 'MQ'  ,  'Martinique'                                      , 'مارتينيك'                                         ,  'MTQ'     ,  596     );
INSERT INTO `country` VALUES(132   , 'MR'  ,  'Mauritania'                                      , 'موريتانيا'                                        ,  'MRT'     ,  222     );
INSERT INTO `country` VALUES(133   , 'MU'  ,  'Mauritius'                                       , 'موريشيوس'                                         ,  'MUS'     ,  230     );
INSERT INTO `country` VALUES(134   , 'YT'  ,  'Mayotte'                                         , 'مايوت'                                            ,  NULL      ,  269     );
INSERT INTO `country` VALUES(135   , 'MX'  ,  'Mexico'                                          , 'المكسيك'                                          ,  'MEX'     ,  52      );
INSERT INTO `country` VALUES(136   , 'FM'  ,  'Micronesia'                                      , 'مايكرونيزيا'                                      ,  'FSM'     ,  691     );
INSERT INTO `country` VALUES(137   , 'MD'  ,  'Moldova'                                         , 'مولدافيا'                                         ,  'MDA'     ,  373     );
INSERT INTO `country` VALUES(138   , 'MC'  ,  'Monaco'                                          , 'موناكو'                                           ,  'MCO'     ,  377     );
INSERT INTO `country` VALUES(139   , 'MN'  ,  'Mongolia'                                        , 'منغوليا'                                          ,  'MNG'     ,  976     );
INSERT INTO `country` VALUES(140   , 'MS'  ,  'Montserrat'                                      , 'مونتسيرات'                                        ,  'MSR'     ,  1664    );
INSERT INTO `country` VALUES(141   , 'MA'  ,  'Morocco'                                         , 'المغرب'                                           ,  'MAR'     ,  212     );
INSERT INTO `country` VALUES(142   , 'MZ'  ,  'Mozambique'                                      , 'موزمبيق'                                          ,  'MOZ'     ,  258     );
INSERT INTO `country` VALUES(143   , 'MM'  ,  'Myanmar'                                         , 'ميانمار'                                          ,  'MMR'     ,  95      );
INSERT INTO `country` VALUES(144   , 'NA'  ,  'Namibia'                                         , 'ناميبيا'                                          ,  'NAM'     ,  264     );
INSERT INTO `country` VALUES(145   , 'NR'  ,  'Nauru'                                           , 'نورو'                                             ,  'NRU'     ,  674     );
INSERT INTO `country` VALUES(146   , 'NP'  ,  'Nepal'                                           , 'نيبال'                                            ,  'NPL'     ,  977     );
INSERT INTO `country` VALUES(147   , 'NL'  ,  'Netherlands'                                     , 'هولندا'                                           ,  'NLD'     ,  31      );
INSERT INTO `country` VALUES(148   , 'AN'  ,  'Netherlands Antilles'                            , 'جزر الأنتيل الهولندي'                              ,  'ANT'     ,  599     );
INSERT INTO `country` VALUES(149   , 'NC'  ,  'New Caledonia'                                   , 'كاليدونيا الجديدة'                                ,  'NCL'     ,  687     );
INSERT INTO `country` VALUES(150   , 'NZ'  ,  'New Zealand'                                     , 'نيوزيلندا'                                        ,  'NZL'     ,  64      );
INSERT INTO `country` VALUES(151   , 'NI'  ,  'Nicaragua'                                       , 'نيكاراجوا'                                        ,  'NIC'     ,  505     );
INSERT INTO `country` VALUES(152   , 'NE'  ,  'Niger'                                           , 'النيجر'                                           ,  'NER'     ,  227     );
INSERT INTO `country` VALUES(153   , 'NG'  ,  'Nigeria'                                         , 'نيجيريا'                                          ,  'NGA'     ,  234     );
INSERT INTO `country` VALUES(154   , 'NU'  ,  'Niue'                                            , 'ني'                                               ,  'NIU'     ,  683     );
INSERT INTO `country` VALUES(155   , 'NF'  ,  'Norfolk Island'                                  , 'جزيرة نورفولك'                                    ,  'NFK'     ,  672     );
INSERT INTO `country` VALUES(156   , 'MP'  ,  'Northern Mariana Islands'                        , 'جزر ماريانا الشمالية'                             ,  'MNP'     ,  1670    );
INSERT INTO `country` VALUES(157   , 'NO'  ,  'Norway'                                          , 'النرويج'                                          ,  'NOR'     ,  47      );
INSERT INTO `country` VALUES(158   , 'OM'  ,  'Oman'                                            , 'عمان'                                             ,  'OMN'     ,  968     );
INSERT INTO `country` VALUES(159   , 'PK'  ,  'Pakistan'                                        , 'باكستان'                                          ,  'PAK'     ,  92      );
INSERT INTO `country` VALUES(160   , 'PW'  ,  'Palau'                                           , 'بالاو'                                             ,  'PLW'     ,  680     );
INSERT INTO `country` VALUES(161   , 'PS'  ,  'Palestine'                                       , 'فلسطين'                                           ,  NULL      ,  970     );
INSERT INTO `country` VALUES(162   , 'PA'  ,  'Panama'                                          , 'بنما'                                             ,  'PAN'     ,  507     );
INSERT INTO `country` VALUES(163   , 'PG'  ,  'Papua New Guinea'                                , 'بابوا غينيا الجديدة'                              ,  'PNG'     ,  675     );
INSERT INTO `country` VALUES(164   , 'PY'  ,  'Paraguay'                                        , 'باراغواي'                                         ,  'PRY'     ,  595     );
INSERT INTO `country` VALUES(165   , 'PE'  ,  'Peru'                                            , 'بيرو'                                             ,  'PER'     ,  51      );
INSERT INTO `country` VALUES(166   , 'PH'  ,  'Philippines'                                     , 'الفليبين'                                         ,  'PHL'     ,  63      );
INSERT INTO `country` VALUES(167   , 'PN'  ,  'Pitcairn'                                        , 'بيتكيرن'                                          ,  'PCN'     ,  0       );
INSERT INTO `country` VALUES(168   , 'PL'  ,  'Poland'                                          , 'بولونيا'                                          ,  'POL'     ,  48      );
INSERT INTO `country` VALUES(169   , 'PT'  ,  'Portugal'                                        , 'البرتغال'                                         ,  'PRT'     ,  351     );
INSERT INTO `country` VALUES(170   , 'PR'  ,  'Puerto Rico'                                     , 'بورتو ريكو'                                       ,  'PRI'     ,  1787    );
INSERT INTO `country` VALUES(171   , 'QA'  ,  'Qatar'                                           , 'قطر'                                              ,  'QAT'     ,  974     );
INSERT INTO `country` VALUES(172   , 'RE'  ,  'Reunion Island'                                  , 'ريونيون'                                          ,  'REU'     ,  262     );
INSERT INTO `country` VALUES(173   , 'RO'  ,  'Romania'                                         , 'رومانيا'                                          ,  'ROM'     ,  40      );
INSERT INTO `country` VALUES(174   , 'RU'  ,  'Russian'                                         , 'روسيا'                                            ,  'RUS'     ,  70      );
INSERT INTO `country` VALUES(175   , 'RW'  ,  'Rwanda'                                          , 'رواندا'                                           ,  'RWA'     ,  250     );
INSERT INTO `country` VALUES(176   , 'KN'  ,  'Saint Kitts and Nevis'                           , 'سانت كيتس ونيفس'                                  ,  'KNA'     ,  1869    );
INSERT INTO `country` VALUES(177   , 'LC'  ,  'Saint Pierre and Miquelon'                       , 'سان بيير وميكلون'                                 ,  'LCA'     ,  1758    );
INSERT INTO `country` VALUES(178   , 'VC'  ,  'Saint Vincent and the Grenadines'                , 'سانت فنسنت وجزر غرينادين'                         ,  'VCT'     ,  1784    );
INSERT INTO `country` VALUES(179   , 'WS'  ,  'Samoa'                                           , 'ساموا'                                            ,  'WSM'     ,  684     );
INSERT INTO `country` VALUES(180   , 'SM'  ,  'San Marino'                                      , 'سان مارينو'                                       ,  'SMR'     ,  378     );
INSERT INTO `country` VALUES(181   , 'ST'  ,  'Sao Tome and Principe'                           , 'ساو تومي وبرينسيبي'                               ,  'STP'     ,  239     );
INSERT INTO `country` VALUES(182   , 'SA'  ,  'Saudi Arabia'                                    , 'المملكة العربية السعودية'                         ,  'SAU'     ,  966     );
INSERT INTO `country` VALUES(183   , 'SN'  ,  'Senegal'                                         , 'السنغال'                                          ,  'SEN'     ,  221     );
INSERT INTO `country` VALUES(184   , 'SC'  ,  'Seychelles'                                      , 'سيشيل'                                            ,  'SYC'     ,  248     );
INSERT INTO `country` VALUES(185   , 'SL'  ,  'Sierra Leone'                                    , 'سيراليون'                                         ,  'SLE'     ,  232     );
INSERT INTO `country` VALUES(186   , 'SG'  ,  'Singapore'                                       , 'سنغافورة'                                         ,  'SGP'     ,  65      );
INSERT INTO `country` VALUES(187   , 'SK'  ,  'Slovakia'                                        , 'سلوفاكيا'                                         ,  'SVK'     ,  421     );
INSERT INTO `country` VALUES(188   , 'SI'  ,  'Slovenia'                                        , 'سلوفينيا'                                         ,  'SVN'     ,  386     );
INSERT INTO `country` VALUES(189   , 'SB'  ,  'Solomon Islands'                                 , 'جزر سليمان'                                       ,  'SLB'     ,  677     );
INSERT INTO `country` VALUES(190   , 'SO'  ,  'Somalia'                                         , 'الصومال'                                          ,  'SOM'     ,  252     );
INSERT INTO `country` VALUES(191   , 'ZA'  ,  'South Africa'                                    , 'جنوب أفريقيا'                                     ,  'ZAF'     ,  27      );
INSERT INTO `country` VALUES(192   , 'GS'  ,  'South Georgia and the South Sandwich'            , 'المنطقة القطبية الجنوبية'                         ,  NULL      ,  0       );
INSERT INTO `country` VALUES(193   , 'ES'  ,  'Spain'                                           , 'إسبانيا'                                          ,  'ESP'     ,  34      );
INSERT INTO `country` VALUES(194   , 'SH'  ,  'Saint Helena'                                    , 'سانت هيلانة'                                       ,  'SHN'     ,  290     );
INSERT INTO `country` VALUES(195   , 'SD'  ,  'Sudan'                                           , 'السودان'                                          ,  'SDN'     ,  249     );
INSERT INTO `country` VALUES(196   , 'SR'  ,  'Suriname'                                        , 'سورينام'                                          ,  'SUR'     ,  597     );
INSERT INTO `country` VALUES(197   , 'SJ'  ,  'Svalbard and Jan Mayen'                          , 'سفالبارد ويان ماين'                               ,  'SJM'     ,  47      );
INSERT INTO `country` VALUES(198   , 'SZ'  ,  'Swaziland'                                       , 'سوازيلند'                                         ,  'SWZ'     ,  268     );
INSERT INTO `country` VALUES(199   , 'SE'  ,  'Sweden'                                          , 'السويد'                                           ,  'SWE'     ,  46      );
INSERT INTO `country` VALUES(200   , 'CH'  ,  'Switzerland'                                     , 'سويسرا'                                           ,  'CHE'     ,  41      );
INSERT INTO `country` VALUES(201   , 'SY'  ,  'Syria'                                           , 'سوريا'                                            ,  'SYR'     ,  963     );
INSERT INTO `country` VALUES(202   , 'TW'  ,  'Taiwan'                                          , 'تايوان'                                           ,  'TWN'     ,  886     );
INSERT INTO `country` VALUES(203   , 'TJ'  ,  'Tajikistan'                                      , 'طاجيكستان'                                        ,  'TJK'     ,  992     );
INSERT INTO `country` VALUES(204   , 'TZ'  ,  'Tanzania'                                        , 'تنزانيا'                                          ,  'TZA'     ,  255     );
INSERT INTO `country` VALUES(205   , 'TH'  ,  'Thailand'                                        , 'تايلندا'                                          ,  'THA'     ,  66      );
INSERT INTO `country` VALUES(206   , 'TL'  ,  'Timor-Leste'                                     , 'تيمور الشرقية'                                    ,  NULL      ,  670     );
INSERT INTO `country` VALUES(207   , 'TG'  ,  'Togo'                                            , 'توغو'                                             ,  'TGO'     ,  228     );
INSERT INTO `country` VALUES(208   , 'TK'  ,  'Tokelau'                                         , 'توكيلاو'                                           ,  'TKL'     ,  690     );
INSERT INTO `country` VALUES(209   , 'TO'  ,  'Tonga'                                           , 'تونغا'                                            ,  'TON'     ,  676     );
INSERT INTO `country` VALUES(210   , 'TT'  ,  'Trinidad and Tobago'                             , 'ترينيداد وتوباغو'                                 ,  'TTO'     ,  1868    );
INSERT INTO `country` VALUES(211   , 'TN'  ,  'Tunisia'                                         , 'تونس'                                             ,  'TUN'     ,  216     );
INSERT INTO `country` VALUES(212   , 'TR'  ,  'Turkey'                                          , 'تركيا'                                            ,  'TUR'     ,  90      );
INSERT INTO `country` VALUES(213   , 'TM'  ,  'Turkmenistan'                                    , 'تركمانستان'                                       ,  'TKM'     ,  7370    );
INSERT INTO `country` VALUES(214   , 'TC'  ,  'Turks and Caicos Islands'                        , 'جزر توركس وكايكوس'                                ,  'TCA'     ,  1649    );
INSERT INTO `country` VALUES(215   , 'TV'  ,  'Tuvalu'                                          , 'توفالو'                                           ,  'TUV'     ,  688     );
INSERT INTO `country` VALUES(216   , 'UG'  ,  'Uganda'                                          , 'أوغندا'                                           ,  'UGA'     ,  256     );
INSERT INTO `country` VALUES(217   , 'UA'  ,  'Ukraine'                                         , 'أوكرانيا'                                         ,  'UKR'     ,  380     );
INSERT INTO `country` VALUES(218   , 'AE'  ,  'United Arab Emirates'                            , 'الإمارات العربية المتحدة'                          ,  'ARE'     ,  971     );
INSERT INTO `country` VALUES(219   , 'GB'  ,  'United Kingdom'                                  , 'المملكة المتحدة'                                  ,  'GBR'     ,  44      );
INSERT INTO `country` VALUES(220   , 'US'  ,  'United States'                                   , 'الولايات المتحدة'                                  ,  'USA'     ,  1       );
INSERT INTO `country` VALUES(221   , 'UM'  ,  'US Minor Outlying Islands'                       , 'قائمة الولايات والمناطق الأمريكية'                  ,  NULL      ,  1       );
INSERT INTO `country` VALUES(222   , 'UY'  ,  'Uruguay'                                         , 'أورغواي'                                          ,  'URY'     ,  598     );
INSERT INTO `country` VALUES(223   , 'UZ'  ,  'Uzbekistan'                                      , 'أوزباكستان'                                       ,  'UZB'     ,  998     );
INSERT INTO `country` VALUES(224   , 'VU'  ,  'Vanuatu'                                         , 'فانواتو'                                          ,  'VUT'     ,  678     );
INSERT INTO `country` VALUES(225   , 'VE'  ,  'Venezuela'                                       , 'فنزويلا'                                           ,  'VEN'     ,  58      );
INSERT INTO `country` VALUES(226   , 'VN'  ,  'Vietnam'                                         , 'فيتنام'                                           ,  'VNM'     ,  84      );
INSERT INTO `country` VALUES(227   , 'VI'  ,  'Virgin Islands (U.S.)'                           , 'الجزر العذراء الأمريكي'                            ,  'VIR'     ,  1340    );
INSERT INTO `country` VALUES(228   , 'VA'  ,  'Vatican City'                                    , 'فنزويلا'                                           ,  'VAT'     ,  39      );
INSERT INTO `country` VALUES(229   , 'WF'  ,  'Wallis and Futuna Islands'                       , 'والس وفوتونا'                                     ,  'WLF'     ,  681     );
INSERT INTO `country` VALUES(230   , 'EH'  ,  'Western Sahara'                                  , 'الصحراء الغربية'                                  ,  'ESH'     ,  212     );
INSERT INTO `country` VALUES(231   , 'YE'  ,  'Yemen'                                           , 'اليمن'                                            ,  'YEM'     ,  967     );
INSERT INTO `country` VALUES(232   , 'ZM'  ,  'Zambia'                                          , 'زامبيا'                                           ,  'ZMB'     ,  260     );
INSERT INTO `country` VALUES(233   , 'ZW'  ,  'Zimbabwe'                                        , 'زمبابوي'                                          ,  'ZWE'     ,  263     );